# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\python_git\Shop_Data_Manage_Project\Login\Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(334, 172)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(9, 70, 81, 31))
        self.label_2.setMinimumSize(QtCore.QSize(70, 0))
        self.label_2.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.txtpassword = QtWidgets.QLineEdit(self.centralwidget)
        self.txtpassword.setGeometry(QtCore.QRect(110, 70, 211, 31))
        self.txtpassword.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txtpassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtpassword.setObjectName("txtpassword")
        self.txtusername = QtWidgets.QLineEdit(self.centralwidget)
        self.txtusername.setGeometry(QtCore.QRect(110, 10, 211, 31))
        self.txtusername.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"selection-color: rgb(170, 170, 255);")
        self.txtusername.setObjectName("txtusername")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(9, 10, 81, 31))
        self.label.setMinimumSize(QtCore.QSize(70, 0))
        self.label.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.btnLogin = QtWidgets.QPushButton(self.centralwidget)
        self.btnLogin.setGeometry(QtCore.QRect(110, 130, 93, 28))
        self.btnLogin.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.btnLogin.setObjectName("btnLogin")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(240, 130, 81, 28))
        self.pushButton_2.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pushButton_2.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Password"))
        self.label.setText(_translate("MainWindow", "User Name"))
        self.btnLogin.setText(_translate("MainWindow", "Login"))
        self.pushButton_2.setText(_translate("MainWindow", "Close"))
