# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\python_git\Shop_Data_Manage_Project\MainWindow\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(906, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mdiArea = QtWidgets.QMdiArea(self.centralwidget)
        self.mdiArea.setObjectName("mdiArea")
        self.horizontalLayout.addWidget(self.mdiArea)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 906, 26))
        self.menubar.setObjectName("menubar")
        self.menuBill = QtWidgets.QMenu(self.menubar)
        self.menuBill.setObjectName("menuBill")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        MainWindow.setMenuBar(self.menubar)
        self.actionSale_Bill = QtWidgets.QAction(MainWindow)
        self.actionSale_Bill.setObjectName("actionSale_Bill")
        self.actionPurchase_Bill = QtWidgets.QAction(MainWindow)
        self.actionPurchase_Bill.setObjectName("actionPurchase_Bill")
        self.actionNew_User = QtWidgets.QAction(MainWindow)
        self.actionNew_User.setObjectName("actionNew_User")
        self.actionChange_Password = QtWidgets.QAction(MainWindow)
        self.actionChange_Password.setObjectName("actionChange_Password")
        self.actionBlock_User = QtWidgets.QAction(MainWindow)
        self.actionBlock_User.setObjectName("actionBlock_User")
        self.menuBill.addAction(self.actionSale_Bill)
        self.menuBill.addAction(self.actionPurchase_Bill)
        self.menuTools.addAction(self.actionNew_User)
        self.menuTools.addAction(self.actionChange_Password)
        self.menuTools.addAction(self.actionBlock_User)
        self.menubar.addAction(self.menuBill.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuBill.setTitle(_translate("MainWindow", "Bill"))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))
        self.actionSale_Bill.setText(_translate("MainWindow", "Sale_Bill"))
        self.actionPurchase_Bill.setText(_translate("MainWindow", "Purchase_Bill"))
        self.actionNew_User.setText(_translate("MainWindow", "New User"))
        self.actionChange_Password.setText(_translate("MainWindow", "Change_Password"))
        self.actionBlock_User.setText(_translate("MainWindow", "Block_User"))
