# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\python_git\Shop_Data_Manage_Project\Change_Password\Change_Password.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(365, 248)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(11, 10, 100, 31))
        self.label.setMinimumSize(QtCore.QSize(100, 0))
        self.label.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.txtoldpassword = QtWidgets.QLineEdit(self.centralwidget)
        self.txtoldpassword.setGeometry(QtCore.QRect(131, 60, 221, 31))
        self.txtoldpassword.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txtoldpassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtoldpassword.setObjectName("txtoldpassword")
        self.btnchange = QtWidgets.QPushButton(self.centralwidget)
        self.btnchange.setGeometry(QtCore.QRect(131, 210, 93, 28))
        self.btnchange.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(221, 221, 221);")
        self.btnchange.setObjectName("btnchange")
        self.txtpassword1 = QtWidgets.QLineEdit(self.centralwidget)
        self.txtpassword1.setGeometry(QtCore.QRect(131, 160, 221, 31))
        self.txtpassword1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txtpassword1.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtpassword1.setObjectName("txtpassword1")
        self.txtpassword = QtWidgets.QLineEdit(self.centralwidget)
        self.txtpassword.setGeometry(QtCore.QRect(131, 110, 221, 31))
        self.txtpassword.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txtpassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtpassword.setObjectName("txtpassword")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 160, 101, 31))
        self.label_4.setMinimumSize(QtCore.QSize(100, 0))
        self.label_4.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"")
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.cmbusername = QtWidgets.QComboBox(self.centralwidget)
        self.cmbusername.setGeometry(QtCore.QRect(131, 10, 221, 31))
        self.cmbusername.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cmbusername.setObjectName("cmbusername")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(11, 60, 100, 31))
        self.label_2.setMinimumSize(QtCore.QSize(100, 0))
        self.label_2.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"font: 75 8pt \"MS Shell Dlg 2\";\n"
"font: 9pt \"MS Shell Dlg 2\";\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 110, 101, 31))
        self.label_3.setMinimumSize(QtCore.QSize(100, 0))
        self.label_3.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"")
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(261, 210, 93, 28))
        self.pushButton_2.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(217, 217, 217);")
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pushButton_2.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "User Name"))
        self.btnchange.setText(_translate("MainWindow", "Change "))
        self.label_4.setText(_translate("MainWindow", "Password"))
        self.label_2.setText(_translate("MainWindow", "Old Password"))
        self.label_3.setText(_translate("MainWindow", "Password"))
        self.pushButton_2.setText(_translate("MainWindow", "Close "))
